# Upload new source language strings to Localazy on push, pull_request in(to) develop branch

name: Localazy Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
    paths: [ lang/en/**.php, lang/en.json ]

  pull_request:
    branches: [ develop ]
    paths: [ lang/en/**.php, lang/en.json ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "localazy-upload"
  localazy-upload:
    # Human-readable name of the job
    name: Upload source language strings to Localazy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
